/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	
	public static void main(String arg[]) {
		System.out.println("lab8 kim");
	}
	
    public boolean someLibraryMethod() {
    	System.out.println("lab8 kim");
        return true;
    }
}
